### PR TITLE
add OWNERS file to the repository

### PR DESCRIPTION
**Pull request by agarwal-mudit**
Mainly required for prow.

Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
@agarwal-mudit This should be on downstream repo not on csi-addons?

**Comment by agarwal-mudit** [comment]
I thought you can use it in future. If not then I will put it there only.

**Comment by Madhu-1** [comment]
Yes please, this is not useful in upstream as we don't use the owner file for anything. Closing it for same. Thank you :)

**Pull request closed without merging**
