### PR TITLE
use github.com/csi-addons/spec v0.1.0 release

### PR DESCRIPTION
**Pull request by Rakshith-R**
Signed-off-by: Rakshith R <rar@redhat.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
No changes in vendor directory is required?

**Comment by Rakshith-R** [comment]
> No changes in vendor directory is required?

There was no vendor directory, added it now.

**Comment by Madhu-1** [comment]
Sorry, i forgot we don't push vendor directory here. can you please revert the last commit?

**Review by Madhu-1 — APPROVED** [review]

**Comment by Rakshith-R** [comment]
done :+1:

**Pull request merged**
